/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: image.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "image.pb-c.h"
void   vma_entry__init
                     (VmaEntry         *message)
{
  static const VmaEntry init_value = VMA_ENTRY__INIT;
  *message = init_value;
}
size_t vma_entry__get_packed_size
                     (const VmaEntry *message)
{
  assert(message->base.descriptor == &vma_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vma_entry__pack
                     (const VmaEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vma_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vma_entry__pack_to_buffer
                     (const VmaEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vma_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VmaEntry *
       vma_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VmaEntry *)
     protobuf_c_message_unpack (&vma_entry__descriptor,
                                allocator, len, data);
}
void   vma_entry__free_unpacked
                     (VmaEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vma_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fdinfo_entry__init
                     (FdinfoEntry         *message)
{
  static const FdinfoEntry init_value = FDINFO_ENTRY__INIT;
  *message = init_value;
}
size_t fdinfo_entry__get_packed_size
                     (const FdinfoEntry *message)
{
  assert(message->base.descriptor == &fdinfo_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fdinfo_entry__pack
                     (const FdinfoEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fdinfo_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fdinfo_entry__pack_to_buffer
                     (const FdinfoEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fdinfo_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FdinfoEntry *
       fdinfo_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FdinfoEntry *)
     protobuf_c_message_unpack (&fdinfo_entry__descriptor,
                                allocator, len, data);
}
void   fdinfo_entry__free_unpacked
                     (FdinfoEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fdinfo_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fdinfo__init
                     (Fdinfo         *message)
{
  static const Fdinfo init_value = FDINFO__INIT;
  *message = init_value;
}
size_t fdinfo__get_packed_size
                     (const Fdinfo *message)
{
  assert(message->base.descriptor == &fdinfo__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fdinfo__pack
                     (const Fdinfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fdinfo__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fdinfo__pack_to_buffer
                     (const Fdinfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fdinfo__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fdinfo *
       fdinfo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fdinfo *)
     protobuf_c_message_unpack (&fdinfo__descriptor,
                                allocator, len, data);
}
void   fdinfo__free_unpacked
                     (Fdinfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fdinfo__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mm_struct__init
                     (MmStruct         *message)
{
  static const MmStruct init_value = MM_STRUCT__INIT;
  *message = init_value;
}
size_t mm_struct__get_packed_size
                     (const MmStruct *message)
{
  assert(message->base.descriptor == &mm_struct__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mm_struct__pack
                     (const MmStruct *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mm_struct__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mm_struct__pack_to_buffer
                     (const MmStruct *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mm_struct__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MmStruct *
       mm_struct__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MmStruct *)
     protobuf_c_message_unpack (&mm_struct__descriptor,
                                allocator, len, data);
}
void   mm_struct__free_unpacked
                     (MmStruct *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mm_struct__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   image__init
                     (Image         *message)
{
  static const Image init_value = IMAGE__INIT;
  *message = init_value;
}
size_t image__get_packed_size
                     (const Image *message)
{
  assert(message->base.descriptor == &image__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t image__pack
                     (const Image *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &image__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t image__pack_to_buffer
                     (const Image *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &image__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Image *
       image__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Image *)
     protobuf_c_message_unpack (&image__descriptor,
                                allocator, len, data);
}
void   image__free_unpacked
                     (Image *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &image__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor vma_entry__field_descriptors[5] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(VmaEntry, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(VmaEntry, end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pgoff",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(VmaEntry, pgoff),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prot",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VmaEntry, prot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VmaEntry, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vma_entry__field_indices_by_name[] = {
  1,   /* field[1] = end */
  4,   /* field[4] = flags */
  2,   /* field[2] = pgoff */
  3,   /* field[3] = prot */
  0,   /* field[0] = start */
};
static const ProtobufCIntRange vma_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor vma_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vma_entry",
  "VmaEntry",
  "VmaEntry",
  "",
  sizeof(VmaEntry),
  5,
  vma_entry__field_descriptors,
  vma_entry__field_indices_by_name,
  1,  vma_entry__number_ranges,
  (ProtobufCMessageInit) vma_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fdinfo_entry__field_descriptors[3] =
{
  {
    "fd",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FdinfoEntry, fd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FdinfoEntry, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(FdinfoEntry, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fdinfo_entry__field_indices_by_name[] = {
  0,   /* field[0] = fd */
  1,   /* field[1] = flags */
  2,   /* field[2] = offset */
};
static const ProtobufCIntRange fdinfo_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor fdinfo_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fdinfo_entry",
  "FdinfoEntry",
  "FdinfoEntry",
  "",
  sizeof(FdinfoEntry),
  3,
  fdinfo_entry__field_descriptors,
  fdinfo_entry__field_indices_by_name,
  1,  fdinfo_entry__number_ranges,
  (ProtobufCMessageInit) fdinfo_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fdinfo__field_descriptors[1] =
{
  {
    "fdinfo_entries",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fdinfo, n_fdinfo_entries),
    offsetof(Fdinfo, fdinfo_entries),
    &fdinfo_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fdinfo__field_indices_by_name[] = {
  0,   /* field[0] = fdinfo_entries */
};
static const ProtobufCIntRange fdinfo__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor fdinfo__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fdinfo",
  "Fdinfo",
  "Fdinfo",
  "",
  sizeof(Fdinfo),
  1,
  fdinfo__field_descriptors,
  fdinfo__field_indices_by_name,
  1,  fdinfo__number_ranges,
  (ProtobufCMessageInit) fdinfo__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mm_struct__field_descriptors[3] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MmStruct, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MmStruct, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vma_entries",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MmStruct, n_vma_entries),
    offsetof(MmStruct, vma_entries),
    &vma_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mm_struct__field_indices_by_name[] = {
  1,   /* field[1] = size */
  0,   /* field[0] = start */
  2,   /* field[2] = vma_entries */
};
static const ProtobufCIntRange mm_struct__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mm_struct__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mm_struct",
  "MmStruct",
  "MmStruct",
  "",
  sizeof(MmStruct),
  3,
  mm_struct__field_descriptors,
  mm_struct__field_indices_by_name,
  1,  mm_struct__number_ranges,
  (ProtobufCMessageInit) mm_struct__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor image__field_descriptors[2] =
{
  {
    "fileinfo",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Image, fileinfo),
    &fdinfo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "meminfo",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Image, meminfo),
    &mm_struct__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned image__field_indices_by_name[] = {
  0,   /* field[0] = fileinfo */
  1,   /* field[1] = meminfo */
};
static const ProtobufCIntRange image__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor image__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "image",
  "Image",
  "Image",
  "",
  sizeof(Image),
  2,
  image__field_descriptors,
  image__field_indices_by_name,
  1,  image__number_ranges,
  (ProtobufCMessageInit) image__init,
  NULL,NULL,NULL    /* reserved[123] */
};
